### ISSUE TITLE
Black Screen on SCPH-30000

### ISSUE THREAD

**Issue by DraconicNEO** [HowlingWolfHWC/HWC-Language-Selector#2]
I tried testing the app on my SCPH-30000 PS2 and it just booted to a black screen

**Comment by HowlingWolfHWC** [comment]
Where you launched it from? Also, does your console has a modchip?
If you prefer, I can assist you at the PS2 Scene Discord too.

**Comment by DraconicNEO** [comment]
Was confirmed to be an issue with the Enceladus engine not running on some PS2s, hopefully it'll be updated to include the new Enceladus patch.

**Comment by HowlingWolfHWC** [comment]
Updated!

**Comment by ab310714gz4700** [comment]
Same with SCPH-35004
