### ISSUE TITLE
Language Selection not Saving

### ISSUE THREAD

**Issue by DraconicNEO** [HowlingWolfHWC/HWC-Language-Selector#3]
When I tried to change the language on my SCPH-77001 PS2 it didn't seem to save the language configuration because when I exited the software and uLE back to OSDSYS the Language was still set to English. Originally I was trying to change the Language to Japanese, which is normally unsupported on US/Asia Systems but I found that even on languages that are supported it still fails to save and the OSDSYS still shows up in English.

I tried with multiple Memory cards and different loading methods but still get the same result.

The Rom version of this PS2 is `0220AC20060210` in case this helps.

**Comment by HowlingWolfHWC** [comment]
The OSDSYS will always load the language saved in the NVM.
My Language Selector applies the language only to memory, which means that it will last there (and work on games and apps) until you launch the OSDSYS or FMCB.

**Comment by DraconicNEO** [comment]
Oh, I see. I thought it changed the Language configuration on OSDSYS, guess I was wrong about that.
